on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        uses: docker://xavidop/alexa-ask-aws-cli:2.12.0
        run: |
          echo $pwd