on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        uses: xavidop/alexa-ask-aws-cli-docker@v1
        with:
          ask-cli-version: '2.13.0'
      - run: |
          echo $pwd;
          node -v